### ISSUE TITLE
playbackRate Is Always 1.0

### ISSUE THREAD

**Issue by cibersheep** [ubports/qtubuntu-media#1]
I can't seem to be able to set property [playbackRate](https://github.com/ubports/qtubuntu-media/blob/xenial/src/aal/aalmediaplayercontrol.cpp#L173) to any other value other than default.

More info https://doc.qt.io/qt-5/qml-qtmultimedia-mediaplayer.html#playbackRate-prop
Qt5.9 upstream: https://github.com/qt/qtmultimedia/blob/5.9/src/multimedia/playback/qmediaplayer.cpp#L809

**Comment by cibersheep** [comment]
Brian says probably the issue might be here and how to call the gstreamer with the playback rate:
https://github.com/ubports/qtubuntu-media/blob/xenial/src/aal/aalmediaplayercontrol.cpp#L178

**Comment by mardy** [comment]
Closing, this issue is now tracked in https://gitlab.com/ubports/core/qtubuntu-media/-/issues/1
