### ISSUE TITLE
Switch to libmedia-hub-qt

### ISSUE THREAD

**Issue by mardy** [ubports/qtubuntu-media#8]

**Comment by j2g2rp** [comment]
Could it generate a regression on music app?
I tested it on Volla X (RC 2021-52) and on pinephone devel (22-01-04)
I noticed that on devel and on RC, when you click over a song on "all songs" view the interface got stucked during some seconds untill the track is reproduced, after that the "all songs" view get stucked like you made a long click over the song displaying the selection options on the songs but not the selection settings on the top bar. To exit from that middle state you have to change to other view or making a long click over a song.

this is how the view got "stucked"
![imagen](https://user-images.githubusercontent.com/28528967/148083476-70157d19-cfcf-4c16-b169-f797b614d972.png)
and this is how the selection view looks usually

![imagen](https://user-images.githubusercontent.com/28528967/148083690-f89c1216-8ca3-428f-9a5c-bae7e5824c78.png)

I have tested it on Volla X also on stable and it doesn't happen.
Tell me If you need further information or I should make the report in to another site.

**Comment by mardy** [comment]
> Could it generate a regression on music app?

Hi @j2g2rp, thanks for the report, but unfortunately it's not clear to me what is happening. If I click on a track, playback starts almost immediately here. Would you be able to record a video, which would show what the problem is?
