### ISSUE TITLE
HTTP Headers are not passed on for streaming purposes

### ISSUE THREAD

**Issue by fredldotme** [ubports/qtubuntu-media#9]
In some cases it is necessary to provide HTTP headers to playback requests, for example in GhostCloud where
file details might expose a multimedia preview of the selected file.

Fixed by: https://github.com/ubports/qtubuntu-media/pull/6

**Comment by Flohack74** [comment]
Any instructions for testers?

**Comment by fredldotme** [comment]
> Any instructions for testers?

This is a behavior change in a developer API sense.
I will push a new version of GhostCloud to showcase the feature pretty soon.

**Comment by mardy** [comment]
Let's close this, since the PR has been merged. If there's still something to be done, please reopen a new issue in gitlab.

**Comment by Flohack74** [comment]
As it does not affect existing code I moved it to Done ;)
